aws_account_id                  = "484087913619"
aws_region                      = "us-east-2"
aws_profile                     = "Admin"
cluster_name                    = "test"
cluster_version                 = "1.30"
cluster_endpoint_private_access = true
cluster_endpoint_public_access  = true
eks_node_group_instance_type    = "c4.2xlarge"
eks_node_group_desired_size     = 1
eks_node_group_max_size         = 2
eks_node_group_min_size         = 1
eks_node_group_ami_type         = "AL2_x86_64"
vpc_name                        = "test-vpc"
vpc_cidr                        = "10.0.0.0/16"
vpc_azs                         = ["us-east-2a", "us-east-2b", "us-east-2c"]
vpc_private_subnets             = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
vpc_public_subnets              = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
vpc_enable_nat_gateway          = true
vpc_enable_dns_hostnames        = true
ecr_repository_name             = "test-repo"
ecr_pull_role_name              = "test-ecr-pull-role"
github_actions_role_name        = "test-github-actions-role"
argocd_app_version              = "6.7.3"